name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"🚀 Ny push till actions-lab av ${{ github.actor }}\"}" \
          "${{ secrets.DISCORD_WEBHOOK }}"
